export type AppId = "strong" | "hevy" | "fitbod" | "jefit" | "stronglifts" | "boostcamp" | "alpha" | "nike" | "freeletics" | "sweat";
export type Reference = {
  id: AppId;
  name: string;
  pattern: string;
  observed: string;
  adaptation: string;
  benefit: string;
  cost: string;
  evidence: string;
  sources: { label: string; url: string }[];
};
export const references: Reference[] = [
  { id: "strong", name: "Strong", pattern: "The workout notebook", observed: "Exercises contain editable set rows, with completion separate from entering values. Sets can be added and tagged.", adaptation: "A compact, continuous ledger with a previous-performance column and inline completion buttons.", benefit: "Fast scanning and correction across the workout.", cost: "Small cells require precise taps; long sessions become long pages.", evidence: "Official workout tutorial and product site. Layout is interpreted, not an installed-app capture.", sources: [{ label: "Workout tutorial", url: "https://help.strongapp.io/article/229-my-first-workout" }, { label: "Product / reach", url: "https://www.strong.app/" }] },
  { id: "hevy", name: "Hevy", pattern: "Exercise cards + live totals", observed: "Live workouts show duration, set count and volume. Exercise notes, previous values, row checkmarks and per-exercise rest settings sit near logging.", adaptation: "Roomier exercise cards, a session metrics strip and a persistent rest strip after logging.", benefit: "Balances workout overview with detailed set entry.", cost: "More labels and controls compete for space.", evidence: "Official illustrated logging and timer guides.", sources: [{ label: "Logging guide", url: "https://www.hevyapp.com/features/track-workouts/" }, { label: "Rest timer", url: "https://www.hevyapp.com/features/workout-rest-timer/" }] },
  { id: "fitbod", name: "Fitbod", pattern: "Exercise detail first", observed: "The exercise details page includes a demonstration, editable sets/reps/weight, rest access and effort feedback. Logging starts rest.", adaptation: "A large equipment illustration above a focused editor, with optional reps-in-reserve input. Illustration replaces video in this study.", benefit: "Keeps movement context and entry together.", cost: "Media uses space; other exercises need navigation.", evidence: "Official exercise-detail guidance and rest-timer help; no recommendation engine reproduced.", sources: [{ label: "Exercise detail guidance", url: "https://help.fitbod.me/hc/en-us/sections/360001927994-Getting-Started" }, { label: "Rest timer", url: "https://help.fitbod.me/hc/en-us/articles/360006340194-Rest-Timer" }] },
  { id: "jefit", name: "JEFIT", pattern: "Logging console", observed: "JEFIT documents a collapsible demonstration, pre-log set editing and a timer panel that changes to rest after logging.", adaptation: "Foldable illustration, editable set ledger, then a large log/rest action area.", benefit: "Useful detail without permanently sacrificing editor space.", cost: "More modes and controls to learn.", evidence: "Official December 2023 redesign article; current store notes still describe the log-button timer. Exact current screen not verified.", sources: [{ label: "Exercise-screen redesign", url: "https://www.jefit.com/blog/upcoming-enhancements-revamped-workout-tab-and-improved-exercise-screens" }, { label: "Current store description", url: "https://apps.apple.com/us/app/jefit-workout-planner-gym-log/id449810000" }] },
  { id: "stronglifts", name: "StrongLifts", pattern: "Tap a set circle", observed: "Sets are large circles. Tapping logs a set; repeated taps reduce reps; holding permits further edits. Rest begins after logging.", adaptation: "Large set circles plus an explicit editor for corrections. Repeated-tap rep reduction is deliberately replaced by labeled controls.", benefit: "Very quick completion of repeated targets.", cost: "Less suited to many different weights or set types.", evidence: "Official app page and timer help.", sources: [{ label: "Set-circle interaction", url: "https://stronglifts.com/app/" }, { label: "Rest timer", url: "https://support.stronglifts.com/article/39-timer" }] },
  { id: "boostcamp", name: "Boostcamp", pattern: "Program prescription", observed: "Sessions lay out prescribed exercises, sets, reps and rest. The app includes RPE tracking, demonstrations and progression tools.", adaptation: "Week/day context, target-versus-actual set rows and an optional effort rating. All program targets are fictional.", benefit: "Makes a structured plan easy to follow.", cost: "Program context is overhead for an improvised session.", evidence: "Official homepage and published workout-logging illustration.", sources: [{ label: "Program and logging workflow", url: "https://www.boostcamp.app/" }] },
  { id: "alpha", name: "Alpha Progression", pattern: "Next-set recommendation", observed: "Provides set-by-set weight/repetition recommendations, optionally with RIR, based on previous performance. First attempts have no recommendation.", adaptation: "Previous / suggested / actual values stay distinct, with an explicit Use suggestion action and optional RIR.", benefit: "Answers what to attempt next while preserving user choice.", cost: "Adds information and would require a real recommendation system.", evidence: "Official fact sheet and progression glossary. Suggestions here are fixed sample values, not training advice.", sources: [{ label: "Progression recommendations", url: "https://alphaprogression.com/en/glossary/progression-recommendations" }, { label: "Fact sheet / reach", url: "https://alphaprogression.com/en/fact-sheet" }] },
  { id: "nike", name: "Nike Training Club", pattern: "Circuit whiteboard", observed: "Whiteboard workouts present circuit purpose, sets and reps with optional movement demonstration videos; class workouts use a different format.", adaptation: "A numbered circuit overview with the current movement expanded. Weight logging is our addition, not an attributed NTC feature.", benefit: "The whole sequence remains easy to understand.", cost: "Less direct for changing individual strength-set values.", evidence: "Official NTC format description; this studies Whiteboard, not video classes.", sources: [{ label: "Whiteboard format", url: "https://www.nike.com/help/a/ntc-info/app" }] },
  { id: "freeletics", name: "Freeletics", pattern: "One movement at a time", observed: "Coach sessions use prescribed work and feedback to inform future sessions. Official training-flow discussions describe exercise/interval completion navigation.", adaptation: "A large repetition target, movement illustration and explicit completion action. Weight fields are added for our journal; no Coach behavior is simulated.", benefit: "Low attention cost during a guided session.", cost: "Hides the full set ledger and makes revisiting work less direct.", evidence: "Official feedback article plus older official forum flow discussion. Exact current active-screen geometry is unverified.", sources: [{ label: "Workout feedback", url: "https://www.freeletics.com/en/blog/posts/what-is-the-purpose-of-the-feedback-i-am-asked-to-give-after-each-workout/" }, { label: "Training-flow discussion", url: "https://forum.freeletics.com/t/update-to-the-app-training-flow-ab-test-android-only/6051" }] },
  { id: "sweat", name: "Sweat", pattern: "Circuit player + up next", observed: "Sweat supports circuit programs, exercise demonstrations and substitutions. Its High Intensity format uses timed circuits and breaks.", adaptation: "A circuit header, current-movement card and up-next preview. This strength adaptation advances one logged set at a time; it does not implement a timed HIIT program.", benefit: "Keeps the current action and next movement visible.", cost: "Circuit pacing adds concepts our basic journal does not need.", evidence: "Official program and app guides. This represents one training format, not all Sweat programs.", sources: [{ label: "Circuit program structure", url: "https://support.sweat.com/hc/en-us/articles/115007112868-What-is-High-Intensity-with-Kayla-and-how-does-it-work" }, { label: "App guide", url: "https://sweat.com/blogs/community/how-to-use-the-sweat-app" }] },
];
