import type { Exercise } from "../domain";

const essentials: readonly (readonly [string, string, string, string])[] = [
  ["bench-press", "Bench press", "Chest", "Barbell"],
  ["squat", "Back squat", "Legs", "Barbell"],
  ["deadlift", "Deadlift", "Back", "Barbell"],
  ["overhead-press", "Overhead press", "Shoulders", "Barbell"],
  ["row", "Dumbbell row", "Back", "Dumbbell"],
  ["lat-pulldown", "Lat pulldown", "Back", "Cable"],
  ["leg-press", "Leg press", "Legs", "Machine"],
  ["romanian-deadlift", "Romanian deadlift", "Legs", "Barbell"],
  ["biceps-curl", "Biceps curl", "Arms", "Dumbbell"],
  ["triceps-extension", "Triceps extension", "Arms", "Cable"],
  ["lateral-raise", "Lateral raise", "Shoulders", "Dumbbell"],
  ["push-up", "Push-up", "Chest", "Bodyweight"],
];
const additions: readonly (readonly [string, string, string])[] = [
  ["Incline bench press", "Chest", "Barbell"],
  ["Decline bench press", "Chest", "Barbell"],
  ["Dumbbell bench press", "Chest", "Dumbbell"],
  ["Incline dumbbell press", "Chest", "Dumbbell"],
  ["Dumbbell fly", "Chest", "Dumbbell"],
  ["Cable fly", "Chest", "Cable"],
  ["Low cable fly", "Chest", "Cable"],
  ["Chest press", "Chest", "Machine"],
  ["Pec deck", "Chest", "Machine"],
  ["Chest dip", "Chest", "Bodyweight"],
  ["Incline push-up", "Chest", "Bodyweight"],
  ["Pull-up", "Back", "Bodyweight"],
  ["Chin-up", "Back", "Bodyweight"],
  ["Assisted pull-up", "Back", "Machine"],
  ["Barbell row", "Back", "Barbell"],
  ["Seated cable row", "Back", "Cable"],
  ["Chest-supported row", "Back", "Dumbbell"],
  ["T-bar row", "Back", "Machine"],
  ["Close-grip pulldown", "Back", "Cable"],
  ["Straight-arm pulldown", "Back", "Cable"],
  ["Back extension", "Back", "Bodyweight"],
  ["Inverted row", "Back", "Bodyweight"],
  ["Dumbbell pullover", "Back", "Dumbbell"],
  ["Front squat", "Legs", "Barbell"],
  ["Goblet squat", "Legs", "Dumbbell"],
  ["Bulgarian split squat", "Legs", "Dumbbell"],
  ["Reverse lunge", "Legs", "Dumbbell"],
  ["Walking lunge", "Legs", "Dumbbell"],
  ["Step-up", "Legs", "Dumbbell"],
  ["Leg extension", "Legs", "Machine"],
  ["Seated leg curl", "Legs", "Machine"],
  ["Lying leg curl", "Legs", "Machine"],
  ["Hack squat", "Legs", "Machine"],
  ["Hip thrust", "Legs", "Barbell"],
  ["Glute bridge", "Legs", "Bodyweight"],
  ["Standing calf raise", "Legs", "Machine"],
  ["Seated calf raise", "Legs", "Machine"],
  ["Hip abduction", "Legs", "Machine"],
  ["Hip adduction", "Legs", "Machine"],
  ["Sumo deadlift", "Legs", "Barbell"],
  ["Single-leg Romanian deadlift", "Legs", "Dumbbell"],
  ["Dumbbell shoulder press", "Shoulders", "Dumbbell"],
  ["Arnold press", "Shoulders", "Dumbbell"],
  ["Cable lateral raise", "Shoulders", "Cable"],
  ["Front raise", "Shoulders", "Dumbbell"],
  ["Reverse fly", "Shoulders", "Dumbbell"],
  ["Face pull", "Shoulders", "Cable"],
  ["Reverse pec deck", "Shoulders", "Machine"],
  ["Shoulder press machine", "Shoulders", "Machine"],
  ["Dumbbell shrug", "Shoulders", "Dumbbell"],
  ["Hammer curl", "Arms", "Dumbbell"],
  ["Barbell curl", "Arms", "Barbell"],
  ["Preacher curl", "Arms", "Machine"],
  ["Incline dumbbell curl", "Arms", "Dumbbell"],
  ["Cable curl", "Arms", "Cable"],
  ["Concentration curl", "Arms", "Dumbbell"],
  ["Rope triceps pushdown", "Arms", "Cable"],
  ["Overhead triceps extension", "Arms", "Dumbbell"],
  ["Skull crusher", "Arms", "Barbell"],
  ["Close-grip bench press", "Arms", "Barbell"],
  ["Triceps kickback", "Arms", "Dumbbell"],
  ["Crunch", "Core", "Bodyweight"],
  ["Cable crunch", "Core", "Cable"],
  ["Hanging knee raise", "Core", "Bodyweight"],
  ["Hanging leg raise", "Core", "Bodyweight"],
  ["Reverse crunch", "Core", "Bodyweight"],
  ["Ab wheel rollout", "Core", "Other"],
  ["Russian twist", "Core", "Dumbbell"],
  ["Pallof press", "Core", "Cable"],
  ["Dead bug", "Core", "Bodyweight"],
];
export const defaultExercises: readonly Exercise[] = [
  ...essentials.map(([id, name, category, equipment]) => ({
    id,
    name,
    category,
    equipment,
    custom: false,
  })),
  ...additions.map(([name, category, equipment]) => ({
    id: name.toLowerCase().replaceAll(/[^a-z0-9]+/g, "-"),
    name,
    category,
    equipment,
    custom: false,
  })),
];
