/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

// Custom route params parsers
type Param_settingsSection = _ExtractParamParserType<typeof import('./app/route-params/settings-section.ts').parser>
type Param_workoutView = _ExtractParamParserType<typeof import('./app/route-params/workout-view.ts').parser>

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {
      'settings-section': { type: Param_settingsSection }
      'workout-view': { type: Param_workoutView }
    }
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'fallback': RouteRecordInfo<
      'fallback',
      '/:pathMatch(.*)',
      { pathMatch: string },
      { pathMatch: string },
      | never
    >,
    'exercises': RouteRecordInfo<
      'exercises',
      '/exercises',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'progress': RouteRecordInfo<
      'progress',
      '/progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'session': RouteRecordInfo<
      'session',
      '/session',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings': RouteRecordInfo<
      'settings',
      '/settings/:section?',
      { section: Exclude<Param_settingsSection, unknown[] | null> | null },
      { section: Exclude<Param_settingsSection, unknown[] | null> | null },
      | never
    >,
    'workouts': RouteRecordInfo<
      'workouts',
      '/workouts',
      { view?: Exclude<Param_workoutView, unknown[] | null> },
      { view: Exclude<Param_workoutView, unknown[] | null> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...pathMatch].vue': {
      routes:
        | 'fallback'
      views:
        | never
      pathParamNames:
        | 'pathMatch'
    }
    'src/pages/ExercisesRoute.vue': {
      routes:
        | 'exercises'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ProgressRoute.vue': {
      routes:
        | 'progress'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/SessionRoute.vue': {
      routes:
        | 'session'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/[[section=settings-section]].vue': {
      routes:
        | 'settings'
      views:
        | never
      pathParamNames:
        | 'section'
    }
    'src/pages/WorkoutsRoute.vue': {
      routes:
        | 'workouts'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
